### ISSUE TITLE
Cannot build, imported project not found

### ISSUE THREAD

**Issue by jpellegrini** [BrentSeidel/Ada-Lisp#34]
Hello!

When I try to build Ada-Lisp, gprbuild complains about a missing project:

```
$ gprbuild lispq.gpr
lispq.gpr:1:06: imported project file "../BBS-Ada/bbs_raven.gpr" not found
bbs_lisp.gpr:1:06: imported project file "../BBS-Ada/bbs_raven.gpr" not found
bbs_lisp.gpr:1:06: imported by "/home/jeronimo/pkg/Ada-Lisp/bbs_lisp.gpr"
bbs_lisp.gpr:1:06: imported by "/home/jeronimo/pkg/Ada-Lisp/lispq.gpr"
gprbuild: "lispq.gpr" processing failed
```

Anyway - perhaps it would also be nice to have simple build instructions in the `README`? For example, for people who know Lisp but not Ada (those people would really benefit from reading and experimenting with Ada-Lisp, but they may not even know what gprbuild is :)

**Comment by BrentSeidel** [comment]
I will update the README to list the other GitHub items that this depends on.

**Comment by BrentSeidel** [comment]
I've added a section about dependencies and building.  Let me know if this helps.

**Comment by jpellegrini** [comment]
Thanks a lot for the quick answer! (And this seems like a really col project, by the way)

gprbuild now doesn't complain about that, but it seem that it's not finding something:

```
$ gprbuild lispq.gpr
lispq.gpr:7:23: object directory "obj" not found
bbs_lisp.gpr:8:23: object directory "obj" not found
bbs_lisp.gpr:9:24: library directory "/home/jeronimo/pkg/BBS-Ada/Ada-Lisp/lib/" does not exist
gprbuild: "lispq.gpr" processing failed
```

```
$ ll ..
total 0
drwxr-xr-x 1 jeronimo jeronimo 220 Jun  2 06:01 Ada-Lisp
drwxr-xr-x 1 jeronimo jeronimo 504 Jun  2 16:43 BBS-Ada
```

(I ran `gprbuild bbs_raven.gpr` inside `BBS-Ada` and it completed successfully; but going back to `Ada-Lisp` and running `gprbuild lispq.gpr` fails,  as shown above)

**Comment by BrentSeidel** [comment]
I believe that you need to create the "lib" and "obj" directories first.  It's a once and done sort of thing so I tend to forget about them.  Can you create them and let me know if it works?  If it does, I'll update the README with that as well.

**Comment by jpellegrini** [comment]
> Can you create them and let me know if it works?

Yes! Works perfectly, thank you!

**Comment by BrentSeidel** [comment]
README is updated with a bit of explanation for these two directories.  It's good to get someone else to take a look at this to find these sort of things.  If you're happy, I'll close the issue.  Thanks.

**Comment by jpellegrini** [comment]
Yes, it's perfect! Thanks a lot.
